### ISSUE TITLE
Could you tell me whether your program can be used to generate the procedures without using sqlcmd

### ISSUE THREAD

**Issue by goonover** [VoltDB/app-debug-and-test#2]
Hello, I am new to Voltdb and I found your program.Although I have read a part of code for a while, I couldn't figure out what's the SQLCommandHack can be used for.And I was wondering if I can use it to load classes and generate procedures, Can you tell me whether it is  workable?

**Comment by benjaminballard** [comment]
Hi, 

The SQLCommandHack class is a copy and paste from VoltDB's SQLCommand (https://github.com/VoltDB/voltdb/blob/master/src/frontend/org/voltdb/utils/SQLCommand.java) taken back in May 2016 which was modified so that the main method could be called from another class more easily.

This entire repo was originally written for a webinar code example, but since has been modified with the compile script so that you can use InProcessVoltDBServer along with SQLCommandHack for unit testing or debugging of stored procedures following the tutorial here: https://github.com/VoltDB/voltdb/wiki/Using-Eclipse-to-Develop,-Unit-Test,-and-Debug-VoltDB-Stored-Procedures-and-Client-Applications

Thanks,
Ben
